
# Use root/example as user/password credentials

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: testdb
    ports:
      - 3307:3306
    volumes:
      - ./WIP/define.sql:/docker-entrypoint-initdb.d/01_define.sql
      - ./WIP/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
